# Ports mapping:
# internal ms: 400X
# external ms: 500X
services:
  # Python preprocessor
  mir:
    container_name: mir
    build:
      context: ./ms/mir/
      dockerfile: Dockerfile
    # ports:
    #   - "4000:kafka-port-here?"

  # GO API
  almaz:
    container_name: almaz
    build:
      context: ./ms/api/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      # Hostname must match with the container_name of mongo
      MONGODB_URI: "mongodb://mongodb:27017"
      PORT: 80
      SECRET: "SUPERSECRETKEYSHOULDNTBEHERE"
      # Uncomment these if exposing the API outwards directly:
      # TLS_KEY_FILE:
      # TLS_CERT_FILE:
      # TLS_PORT:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
