version: '3.8'

services:
  rest_api:
    build: 
      context: ./ms/restfulgo
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MONGODB_URI: "mongodb://db:27017"
      API_HOST: "rest_api"
      PORT: 80
      JWT: "SUPERSECRETKEYSHOULDNTBEHERE" # Only for local use

  db:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      # - ./init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  mongo_data:

