# docker-compose.yaml
services:
  mir:
    container_name: mir
    build:
      context: ./src/mir/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      OR_SECRET: "<redacted>"

  mongodb:
    container_name: mongodb
    image: mongo:8.0.5 # https://hub.docker.com/_/mongo/tags
    networks:
      - net
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  net:
    name: net

volumes:
  mongo_data:
    name: mongo_data
