---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dalmaz"
  namespace: "default"
  labels:
    app: "dalmaz"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dalmaz"
  template:
    metadata:
      labels:
        app: "dalmaz"
    spec:
      containers:
      - name: "calmaz"
        image: "europe-north1-docker.pkg.dev/charged-camera-450710-j1/northstar-repo/almaz:latest"
        env:
        - name: "MONGODB_URI"
          valueFrom:
            secretKeyRef:
              name: gke-secrets   # Name of the secret generated
              key: mongodb_uri    # Key within the secret to use
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "dalmaz-hpa"
  namespace: "default"
  labels:
    app: "dalmaz"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "dalmaz"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "almaz"
  namespace: "default"
  labels:
    app: "dalmaz"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 80
  selector:
    app: "dalmaz"
  type: "ClusterIP"
