---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "almaz"
  namespace: "default"
  labels:
    app: "almaz"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "almaz"
  template:
    metadata:
      labels:
        app: "almaz"
    spec:
      containers:
      - name: "almaz-1"
        image: "europe-north1-docker.pkg.dev/charged-camera-450710-j1/northstar-repo/almaz:latest"
        env:
        - name: "MONGODB_URI"
          valueFrom:
            secretKeyRef:
              key: "MONGODB_URI"
              name: "gke-secrets"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "almaz-hpa-zm2r"
  namespace: "default"
  labels:
    app: "almaz"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "almaz"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "almaz-service"
  namespace: "default"
  labels:
    app: "almaz"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 80
  selector:
    app: "almaz"
  type: "ClusterIP"
