---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dmongo"
  namespace: "default"
  labels:
    app: "dmongo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dmongo"
  template:
    metadata:
      labels:
        app: "dmongo"
    spec:
      containers:
      - name: "cmongo"
        image: "mongo:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "dmongo-hpa"
  namespace: "default"
  labels:
    app: "dmongo"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "dmongo"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb"
  namespace: "default"
  labels:
    app: "dmongo"
spec:
  ports:
  - protocol: "TCP"
    port: 27017
    targetPort: 27017
  selector:
    app: "dmongo"
  type: "ClusterIP"
