
name: Build and Push Multiple Docker Images

on:
  workflow_dispatch:
  # Uncomment to trigger the workflow automatically on pushes to the main branch
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-north1
  GAR_REPOSITORY: northstar-repo
  IMAGE_TAG: latest

jobs:
  build_and_push:
    name: Build and Push Multiple Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          # - gopp
          - rest_api
          - mongodb
    steps:
      # Checkout the repository with submodules if needed
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Debug to list directory structure
      - name: Debug Directory Structure
        run: |
          echo "Listing directory structure..."
          ls -R

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker authentication for Artifact Registry
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev

      # Build and Push Docker Image
      - name: Build and Push Docker Images
        run: |
          IMAGE_URI="${GAR_LOCATION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}"
          echo "Building image for service: ${{ matrix.service }}"

          # Define context path based on service
          if [ "${{ matrix.service }}" = "gopp" ]; then
            CONTEXT="./ms/gopp"
          elif [ "${{ matrix.service }}" = "rest_api" ]; then
            CONTEXT="./ms/api"
          elif [ "${{ matrix.service }}" = "mongodb" ]; then
            CONTEXT="." # MongoDB official image
          else
            echo "Unknown service: ${{ matrix.service }}"
            exit 1
          fi

          echo "Using build context: ${CONTEXT}"

          if [ "${{ matrix.service }}" = "mongodb" ]; then
            echo "Pulling and tagging MongoDB image..."
            docker pull mongo:8.0
            docker tag mongo:8.0 "${IMAGE_URI}"
          else
            echo "Building Docker image ${IMAGE_URI}..."
            docker build --tag "${IMAGE_URI}" "${CONTEXT}"
          fi

          echo "Pushing image ${IMAGE_URI} to Artifact Registry..."
          docker push "${IMAGE_URI}"
