name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: northstar-k8s                          # cluster name
  GKE_ZONE: europe-north1                             # cluster zone
  IMAGE: pypp                                         # Image name (more may have to be added here)
  IMAGE_TAG: ${{ github.head_ref }}.${{ github.sha }} # image tag based of the "branch.commit-sha"
  GAR_ZONE: europe-north1                             # artifact registry zone
  GAR_REPO: northstar-repo                            # artifact registry repository

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    # May be needed for "get-gke-credentials" to work:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    # Setup gcloud CLI 
    # https://github.com/marketplace/actions/authenticate-to-google-cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.8
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    # https://github.com/marketplace/actions/get-gke-credentials
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2.3.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Required for the "docker build" to work
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4.2.2

    # Build the Docker image
    # --tag ...
    #
    - name: Build
      run: |-
        docker build \
          -f /ms/pypp/Dockerfile \
          --tag "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f deploy.yaml
        kubectl get pods
