name: Build and Push Multiple Docker Images

on:
  workflow_dispatch:
  # Uncomment to trigger the workflow automatically on pushes to the main branch
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}         # Google Cloud project ID
  GAR_LOCATION: europe-north1                    # Artifact Registry location (regional)
  GAR_REPOSITORY: northstar-repo                 # Artifact Registry repository name
  IMAGE_TAG: latest                              # Image tag

jobs:
  build_and_push:
    name: Build and Push Multiple Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:                                 # Define services to build in parallel
          - gopp
          - rest_api
          - mongodb
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker Authentication for Artifact Registry
        run: |
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${GAR_LOCATION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}"
          echo "Building image for service: ${{ matrix.service }}"

          # Define the build context based on the service
          if [ "${{ matrix.service }}" = "gopp" ]; then
            CONTEXT="./ms/gopp"
          elif [ "${{ matrix.service }}" = "rest_api" ]; then
            CONTEXT="./ms/restfulgo"
          elif [ "${{ matrix.service }}" = "mongodb" ]; then
            CONTEXT="./" # MongoDB uses its official image; no custom Dockerfile required
          fi

          if [ "${{ matrix.service }}" = "mongodb" ]; then
            # Mongodb direct pull and push
            echo "Pulling MongoDB 8.0 image..."
            docker pull mongo:8.0
            echo "Tagging MongoDB image for Artifact Registry..."
            docker tag mongo:8.0 "${IMAGE_URI}"
          else
            # Build custom images for gopp and rest_api
            echo "Building Docker image..."
            docker build --tag "${IMAGE_URI}" "${CONTEXT}"
          fi

          # Push the image to Artifact Registry
          echo "Pushing the image ${IMAGE_URI} to Artifact Registry..."
          docker push "${IMAGE_URI}"
