# See:
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
# for accessing GitHub default variables!

name: GKE pipeline

on:
  push:
    branches:
      - main
    paths:
      # Only trigger if changes occur in these files/dir
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.py"
      - "**/*.go"
      - "**/Dockerfile"

env:
  # Cluster name
  GKE_CLUSTER: northstar-k8s
  # Cluster zone
  GKE_ZONE: europe-north1

  # image tag based of the "branch.commit-sha"
  # Only a-z, 0-9, _ (underscores), . (periods) and - (hyphens) are allowed.
  # IMAGE_TAG: ${{ github.ref_name || 'default' }}-${{ github.sha }}
  IMAGE_TAG: "latest"
  # Artifact registry zone
  GAR_ZONE: europe-north1
  # Artifact registry repository
  GAR_REPO: northstar-repo

jobs:
  common:
    uses: ./.github/workflows/common.yaml
    with:
      GKE_CLUSTER: $GKE_CLUSTER
      GKE_ZONE: $GKE_ZONE
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

  build:
    name: Build and publish
    needs: common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "almaz", "mir" ]
    steps:
    # Build the Docker image
    # -f -> defines where the Dockerfile is located
    # --tag ...
    # ...
    # dir/nextdir -> defines where the build output will be put
    #                (using the same as the Dockerfile is required if it contains multi-build steps)
    - name: Build ${{ matrix.image }} docker image
      run: |-
        docker build \
          -f ms/${{ matrix.image }}/Dockerfile \
          --tag "$GAR_ZONE-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/$GAR_REPO/${{ matrix.image }}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ms/${{ matrix.image }}/

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GAR_ZONE-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/$GAR_REPO/${{ matrix.image }}"

  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
    # IMPORTANT!
    # Make sure to add the each variable to the CI/CD variables on GitHub.
    - name: Set secrets
      run: |-
        kubectl delete secret gke-secrets || true && \
        kubectl create secret generic gke-secrets --from-literal=MONGODB_URI=${{ secrets.MONGODB_URI }}

    - name: Deploy
      run: |-
        kubectl apply -f k8s/mongodb.yaml -f k8s/almaz.yaml

    - name: Get pods
      run: |-
        kubectl get pods
